- name: install neovim dependencies 
  ansible.builtin.apt:
    pkg:
    - nodejs
    - npm
    - golang
    - ripgrep
    - gopls
    - ccls
    
- name: Install "live-server" npm package globally.
  become: true
  community.general.npm:
    name: live-server 
    global: true
