#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/.config/back.jpg &
picom --backend glx --vsync &
xrdb merge ~/.Xresources &
polybar mybar &
dunst &

xsetroot -cursor_name left_ptr
xset b off
xset r rate 300 50

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#firefox -new-tab -url "https://github.com/divinepaul" -new-tab -url "https://github.com/" &
#alacritty --working-directory ~/projects -e zsh -c "ls | fzf | xargs nvim" &
