#!/bin/bash
bspc subscribe desktop_focus | while read line
do
    desktopId=`echo $line | awk '{print $3}'`
    desktopName=`bspc query -T -d $desktopId | jshon -e name -u`
    notify-send $desktopName -t 300
done
